name: "DannyDing'Blog"
description: "Lightweight theme"

url: 'https://getvkey.github.io' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
paginate: 10
paginate_path: /page/:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: compressed
    sass_dir: assets/css/

