title: DannyDing-Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "DannyDing"
  email: "ucyour@live.com"
  url: "https://getvkey.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "DannyDing"
year : "2018"
